StudentCosmoDBlobStorage/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ViewModel;
using Business;
namespace StudentCosmoDBlobStorage.Controllers
{
    public class StudentsController : Controller
    {
        CosmodbBussines cosmodb = new CosmodbBussines();
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> StudentsList(string stName)
        {
            List<Student> students = await cosmodb.StudentsList(stName);
            return View(students);
        }

        public ActionResult DeletedView(string stName)
        {
            return View(cosmodb.DeleteStudent(stName));
        }

        public ActionResult AddStudent()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddStudent([Bind(Exclude = "UserPhoto")] Student student)
        {
            HttpPostedFileBase uploadFile = Request.Files["UserPhoto"];
            if (uploadFile.ContentLength != 0)
            {
               await cosmodb.AddStudent(uploadFile,student);
                return RedirectToAction("StudentsList");
            }
            else
            {

                ModelState.AddModelError(string.Empty, "Please Select Picture");

                return View(student);
            }
        }

        public ActionResult EditStudent(string DocumentId)
        {
            return View(cosmodb.EditStudent(DocumentId));
        }

        public async Task<ActionResult> De_Activate(string documentId)
        {
            await cosmodb.Deactivate(documentId);
            return RedirectToAction("StudentsList");
        }

        public async Task<ActionResult> DeLeteStudent(string documentId)
        {
            await cosmodb.DeleteStudent(documentId);
            return RedirectToAction("StudentsList");
        }

        public async Task<ActionResult> UpdateAsync(Student Studentz)
        {
            await cosmodb.UpdateAsync(Studentz);
            return RedirectToAction("StudentsList");
        }
    }
}

StudentCosmoDBlobStorage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/css/DropDown.css">
    <title>@ViewBag.Title - DUT REG Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<style>
    .my_text {
        font-family: Arial, Helvetica, sans-serif font-size: 60px;
    }

    background {
        opacity: 0.5;
        filter: alpha(opacity=50); /* For IE8 and earlier */
    }
</style>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<body>
    <div class="my_text">
        <nav class="w3-sidebar w3-black w3-animate-left w3-xxlarge" style="display:none;padding-top:50px;left:0;z-index:2" id="InSidebar">


        </nav>

        <div id="menu" class="w3-black w3-animate-left w3-xxlarge" style="display:none;left:0;z-index:2">
            <ul>
                <li class="butlook" href="javascript:void(0)" onclick="closeNav()" class="w3-button w3-black w3-xxxlarge w3-display-topright" style="padding:0px;  margin-left: 250px;">
                    <i class="fa fa-remove"></i>
                </li>
                @if (User.IsInRole("Administrator"))
                {
                    <li class="butlook">
                        @Html.ActionLink("Administration", "Index", "Admin")<i class="fa fa-caret-right"></i>
                        <ul>
                            <li class="butlook">@Html.ActionLink("View Registered users", "Index", "Admin")
                            <li class="butlook">@Html.ActionLink("Register New Staff", "Create", "Admin")
                            <li class="butlook">@Html.ActionLink("Manage Roles", "ViewAllRoles", "Admin")
                            <li class="butlook">@Html.ActionLink("Deleted Users", "archive", "Admin")

                        </ul>
                    </li>
                }
            </ul>
            <ul>
            </ul>

        </div>



        <div class="w3-top">

            <div class="w3-bar w3-black w3-wide w3-padding w3-card">
                <div class="w3-button w3-padding-16 w3-left" onclick="openNav()">☰</div>
                <a class="w3-bar-item w3-button"><font size="4"><b>D R</b> @Html.ActionLink("DUT REG", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }) </font></a>
                <!-- Float links to the right. Hide them on small screens -->

                <a class="w3-bar-item w3-button"><font size="4">@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }) </font></a>
                <a class="w3-bar-item w3-button"><font size="4">@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }) </font></a>
                <a class="w3-bar-item w3-button"><font size="4">@Html.ActionLink("New student", "AddStudent", "Students", new { area = "" }, new { @class = "navbar-brand" }) </font></a>
                <a class="w3-bar-item w3-button"><font size="4">@Html.ActionLink("Student List", "StudentsList", "Students", new { area = "" }, new { @class = "navbar-brand" }) </font></a>
                @*<a class="w3-bar-item w3-button"><font size="4">@Html.ActionLink("Contact US", "emailComplain", "Emailsender", new { area = "" }, new { @class = "navbar-brand" }) </font></a>*@

                <a class="w3-bar-item w3-button"><font size="4"> @Html.Partial("_LoginPartial")</font></a>

            </div>
        </div>



    </div>

    <br />

    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - DUT REG App</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


    <script>

        function openNav() {
            document.getElementById("menu").style.width = "22%";
            document.getElementById("menu").style.display = "block";
        }

        function closeNav() {
            document.getElementById("menu").style.display = "none";
        }
    </script>
    </>
</html>